abstract class AppStrings {
  static const String appName = 'Bright Minds',
      // boarding
      welcomeTo = 'Welcome To ',
      discoverWorldOfKnowledge =
          'Discover a World of knowledge at your fingertips with \'Bright Minds\' comprehensive learning platform',
      learnFrom = 'Learn From The Best',
      accessHighQuality =
          'Access high-quality courses from top educators and industry experts, anytime, anywhere',
      // auth
      email = 'Email',
      password = 'Password',
      confirmPassword = 'Confirm Password',
      forgotPassword = 'Forgot Password?',
      login = 'Login',
      dontHaveAccount = 'Don\'t have account? ',
      alreadyHaveAccount = 'Already have account? ',
      signUp = 'Sign Up',
      signIn = 'Sign In',
      register = 'Register',
      firstName = 'First Name',
      lastName = 'Last Name',
      resetPassword = 'Reset Password',
      enterEmail = 'Enter Your Email',
      phoneNumber = 'Phone Number',
      reset = 'Reset',
      // app strings
      home = 'Home',
      courses = 'Courses',
      ourTeam = 'Our Team',
      bestOnlineCourses = 'Best Online Courses',
      theBestOnlineLearning = 'The Best Online Learning Platform',
      getEducatedFromHome = 'Get Educated Online From Your Home',
      veroElitr =
          'Vero elitr justo clita lorem. Ipsum dolor at sed stet sit diam no. Kasd rebum ipsum et diam justo clita et kasd rebum sea sanctus eirmod elitr.',
      skilldeInstructors = 'Skilled Instructors',
      onlineClasses = 'Online Classes',
      homeProjects = 'Home Projects',
      bookLibrary = 'Book Library',
      diamElitrKasd =
          'Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam',
      readMore = 'Read More',
      internationalCertificate = 'International Certificate',
      temporErate =
          'Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet',
      temporErateAtClita =
          'Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit.',
      aboutUs = 'About Us',
      webDesign = 'Web Design',
      courses49 = '49 Courses',
      categories = 'Categories',
      coursesCategories = 'Courses Categories',
      students30 = '30 Students',
      hrs = '1.49 Hrs',
      john = 'John Doe',
      webDesingDevelopment = 'Web Design & Development Course for Beginners',
      price = '\$149.00',
      dolorAmetSit = 'Dolor amet sit justo amet elitr clita ipsum elitr est.',
      newSletter = 'Newsletter',
      gallery = 'Gallery',
      infoExample = 'info@example.com',
      number = '+012 345 67890',
      address = '123 Street, New York, USA',
      contact = 'Contact',
      faq = 'FAQs & Help',
      termsCondition = 'Terms & Condition',
      privacyPolicy = 'Privacy Policy',
      contactUs = 'Contact Us',
      quickLink = 'Quick Link',
      profession = 'Profession',
      clientName = 'Client Name',
      ourStudentsSay = 'Our Students Say!',
      testimonial = 'Testimonial',
      designation = 'Designation',
      instructorName = 'Instructor Name',
      instructors = 'Instructors',
      expertInstructors = 'Expert Instructors',
      // anthor
      skip = 'Skip',
      next = 'Next';
}
